# Generated by Django 2.2.3 on 2019-08-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price_hystory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_hystory',
        ),
    ]
