# Generated by Django 2.2.3 on 2019-08-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190803_1416'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishedproduct',
            unique_together={('wish_list', 'product')},
        ),
    ]
