# Generated by Django 2.2.3 on 2019-08-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190803_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishedproduct',
            name='added_to',
            field=models.DateField(auto_now_add=True),
        ),
    ]
