# Generated by Django 2.2.3 on 2019-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20190803_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishedproduct',
            name='added_to',
            field=models.DateField(),
        ),
    ]
