# Generated by Django 2.2.3 on 2019-08-03 20:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20190803_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypricehistory',
            name='end',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
        migrations.AlterField(
            model_name='productpricehistory',
            name='end',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
    ]
