version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ebs
      POSTGRES_PASSWORD: ebs
      POSTGRES_DB: ebs
    ports:
      - 5432:5432
  web:
    build: .
    command: >
      sh -c "
             python3.6 manage.py makemigrations &&
             python3.6 manage.py migrate --run-syncdb &&
             python3.6 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/Django-shop
    ports:
      - "8000:8000"
    depends_on:
      - db