# Generated by Django 2.2.3 on 2019-08-01 12:12

from django.conf import settings
from django.contrib.auth.models import User
from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    initial = True

    def create_super_user(apps, schema_editor):
        # build the user you now have access to via Django magic
        user = User.objects.create_superuser('test', 'test@test.com','test', last_login=timezone.now())
        user.save()

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.RunPython(create_super_user),
    ]
